Added a deprecation notice
mila-iqia/babyai pull request #120
Opened 2023-03-01 15:40 UTC by BolunDai0216

Added a deprecation notice:

> This code base is no longer maintained, and is not expected to be maintained again in the future.
> These environments been maintained inside of Minigrid
> (see https://github.com/Farama-Foundation/Minigrid/tree/master/minigrid/envs/babyai).
> This maintained version includes documentation, support for current versions of Python,
> numerous bug fixes, support for installation via pip, and numerous other large quality of life improvements.
> We encourage researchers to switch to this maintained version for all purposes other than comparing
> to results run on this version of the environments.

when importing the library.

2023-03-01 15:58 UTC, jkterry1 commented
For a bit of context on this (I'm the CEO of Farama, the maintainers of Minigrid), we've had significant past issues with people not reading the readme files for libraries that point to us, so we've started adding warning messages instead

2023-03-01 17:15 UTC, dyth commented on babyai/__init__.py
> +    "These environments been maintained inside of Minigrid"
These environments "have" been maintained inside of MiniGrid?

2023-03-01 17:16 UTC, dyth commented
:wave: Seems reasonable, but I would not be comfortable approving this without hearing @maximecb's opinion first.

2023-03-01 17:53 UTC, maximecb commented
Seems reasonable 👍

2023-03-02 15:27 UTC, dyth requested changes
Please fix the grammatical issue.

2023-03-02 16:18 UTC, BolunDai0216 commented
> Please fix the grammatical issue.

It is now:

> This code base is no longer maintained and is not expected to be maintained again. These environments are now maintained within Minigrid (see https://github.com/Farama-Foundation/Minigrid/tree/master/minigrid/envs/babyai). The maintained version includes documentation, support for current versions of Python, numerous bug fixes, support for installation via pip, and many other quality-of-life improvements. We encourage researchers to switch to the maintained version for all purposes other than comparing with results that use this version of the environments.

Does the current version look good to you?

2023-03-06 16:17 UTC, jkterry1 commented
Hey guys, is this able to be merged now?

2023-03-06 16:36 UTC, merged